version: '2'
services:
  web:
    image: node:latest
    working_dir: /app
    command: npm run dev
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres:latest
    ports:
      - "5432:5432"